using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RESTApiExample
{
    public static class Languages
    {
        public const string AFRIKAANS = "af";
        public const string ALBANIAN = "sq";
        public const string AMHARIC = "am";
        public const string ARABIC = "ar";
        public const string ARMENIAN = "hy";
        public const string AZERBAIJANI = "az";
        public const string BASQUE = "eu";
        public const string BELARUSIAN = "be";
        public const string BENGALI = "bn";
        public const string BIHARI = "bh";
        public const string BULGARIAN = "bg";
        public const string BURMESE = "my";
        public const string CATALAN = "ca";
        public const string CHEROKEE = "chr";
        public const string CHINESE = "zh";
        public const string CHINESE_SIMPLIFIED = "zh-CN";
        public const string CHINESE_TRADITIONAL = "zh-TW";
        public const string CROATIAN = "hr";
        public const string CZECH = "cs";
        public const string DANISH = "da";
        public const string DHIVEHI = "dv";
        public const string DUTCH = "nl";
        public const string ENGLISH = "en";
        public const string ESPERANTO = "eo";
        public const string ESTONIAN = "et";
        public const string FILIPINO = "tl";
        public const string FINNISH = "fi";
        public const string FRENCH = "fr";
        public const string GALICIAN = "gl";
        public const string GEORGIAN = "ka";
        public const string GERMAN = "de";
        public const string GREEK = "el";
        public const string GUARANI = "gn";
        public const string GUJARATI = "gu";
        public const string HEBREW = "iw";
        public const string HINDI = "hi";
        public const string HUNGARIAN = "hu";
        public const string ICELANDIC = "is";
        public const string INDONESIAN = "id";
        public const string INUKTITUT = "iu";
        public const string ITALIAN = "it";
        public const string JAPANESE = "ja";
        public const string KANNADA = "kn";
        public const string KAZAKH = "kk";
        public const string KHMER = "km";
        public const string KOREAN = "ko";
        public const string KURDISH = "ku";
        public const string KYRGYZ = "ky";
        public const string LAOTHIAN = "lo";
        public const string LATVIAN = "lv";
        public const string LITHUANIAN = "lt";
        public const string MACEDONIAN = "mk";
        public const string MALAY = "ms";
        public const string MALAYALAM = "ml";
        public const string MALTESE = "mt";
        public const string MARATHI = "mr";
        public const string MONGOLIAN = "mn";
        public const string NEPALI = "ne";
        public const string NORWEGIAN = "no";
        public const string ORIYA = "or";
        public const string PASHTO = "ps";
        public const string PERSIAN = "fa";
        public const string POLISH = "pl";
        public const string PORTUGUESE = "pt-PT";
        public const string PUNJABI = "pa";
        public const string ROMANIAN = "ro";
        public const string RUSSIAN = "ru";
        public const string SANSKRIT = "sa";
        public const string SERBIAN = "sr";
        public const string SINDHI = "sd";
        public const string SINHALESE = "si";
        public const string SLOVAK = "sk";
        public const string SLOVENIAN = "sl";
        public const string SPANISH = "es";
        public const string SWAHILI = "sw";
        public const string SWEDISH = "sv";
        public const string TAJIK = "tg";
        public const string TAMIL = "ta";
        public const string TAGALOG = "tl";
        public const string TELUGU = "te";
        public const string THAI = "th";
        public const string TIBETAN = "bo";
        public const string TURKISH = "tr";
        public const string UKRAINIAN = "uk";
        public const string URDU = "ur";
        public const string UZBEK = "uz";
        public const string UIGHUR = "ug";
        public const string VIETNAMESE = "vi";
        public const string UNKNOWN = "";

    }
}
